/**
 * Simple text-based PDF-like report renderer.
 * Returns a formatted text report (content-type: text/plain).
 *
 * For production, replace with @react-pdf/renderer or Puppeteer HTML-to-PDF.
 * This avoids the heavy dependency for MVP while providing downloadable reports.
 */

export function renderTextReport(
  group: any,
  expenses: any[],
  settlements: any[],
  memberSummary: { name: string; paid: number; owed: number; net: number }[],
): string {
  const sep = '='.repeat(60);
  const lines: string[] = [];

  lines.push(sep);
  lines.push('  KHARCHA EXPENSE REPORT');
  lines.push(sep);
  lines.push(`  Group: ${group.name}`);
  lines.push(`  Members: ${group.members?.map((m: any) => m.user?.name).join(', ')}`);
  lines.push(`  Exported: ${new Date().toISOString().slice(0, 10)}`);
  lines.push(`  Total Expenses: ${expenses.length}`);

  const totalPaise = expenses.reduce(
    (s: number, e: any) => s + e.amountInPaise,
    0,
  );
  lines.push(`  Total Amount: Rs ${(totalPaise / 100).toFixed(2)}`);
  lines.push('');

  // Per-person breakdown
  lines.push('-'.repeat(60));
  lines.push('  PER-PERSON BREAKDOWN');
  lines.push('-'.repeat(60));
  lines.push(
    `  ${'Member'.padEnd(20)} ${'Paid'.padStart(12)} ${'Owes'.padStart(12)} ${'Net'.padStart(12)}`,
  );
  lines.push('-'.repeat(60));
  for (const m of memberSummary) {
    const net = m.net >= 0 ? `+${(m.net / 100).toFixed(2)}` : `${(m.net / 100).toFixed(2)}`;
    lines.push(
      `  ${m.name.padEnd(20)} ${('Rs ' + (m.paid / 100).toFixed(2)).padStart(12)} ${('Rs ' + (m.owed / 100).toFixed(2)).padStart(12)} ${('Rs ' + net).padStart(12)}`,
    );
  }
  lines.push('');

  // Itemized expenses
  lines.push('-'.repeat(60));
  lines.push('  ITEMIZED EXPENSES');
  lines.push('-'.repeat(60));
  lines.push(
    `  ${'Date'.padEnd(12)} ${'Description'.padEnd(25)} ${'Paid By'.padEnd(12)} ${'Amount'.padStart(10)}`,
  );
  lines.push('-'.repeat(60));
  for (const exp of expenses) {
    lines.push(
      `  ${new Date(exp.date).toISOString().slice(0, 10).padEnd(12)} ${(exp.description || '').slice(0, 24).padEnd(25)} ${(exp.paidBy?.name || '').slice(0, 11).padEnd(12)} ${('Rs ' + (exp.amountInPaise / 100).toFixed(2)).padStart(10)}`,
    );
  }

  if (settlements.length > 0) {
    lines.push('');
    lines.push('-'.repeat(60));
    lines.push('  SETTLEMENTS');
    lines.push('-'.repeat(60));
    for (const s of settlements) {
      lines.push(
        `  ${s.paidBy?.name} -> ${s.paidTo?.name}: Rs ${(s.amountInPaise / 100).toFixed(2)}${s.note ? ` (${s.note})` : ''}`,
      );
    }
  }

  lines.push('');
  lines.push(sep);
  lines.push('  Generated by Kharcha');
  lines.push(sep);

  return lines.join('\n');
}
